deploy:
  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
  runs-on: ubuntu-latest
  needs:
    [build-02, build-04, build-04-dotnet, gen-redirects, gen-component-schema]
  if: ${{ needs.build-02.result == 'success' && needs.build-04.result == 'success' && needs.gen-redirects.result == 'success' && github.ref == 'refs/heads/main' }}
  steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: |
          *-docs
          redirects
          component-schema
          dotnet-dev-docs

    - name: Copy artifacts to deploy folder
      run: |
        mkdir -p deploy/
        for dir in artifacts/*/; do
          cp -r "$dir"* deploy/
        done

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "./deploy"
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
